[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
insert = 1
filetypes = 'snippet'
unite_sources = [ 'neosnippet', 'neosnippet/user', 'neosnippet/runtime']

[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make'
  unix = 'make'
  linux = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'


[[plugins]]
repo = 'quickrun.vim'

[[plugins]]
repo = 'ref.vim'

[[plugins]]
repo = 'tsaleh/vim-align'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'ZenCoding.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'kana/vim-altr'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'h1mesuke/textobj-wiw'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'thinca/vim-singleton'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'tanabe/ToggleCase-vim'

[[plugins]]
repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'

