[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
insert = 1
filetypes = 'snippet'
unite_sources = [ 'neosnippet', 'neosnippet/user', 'neosnippet/runtime']

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'quickrun.vim'

[[plugins]]
repo = 'tsaleh/vim-align'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'kana/vim-altr'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'h1mesuke/textobj-wiw'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'tanabe/ToggleCase-vim'

[[plugins]]
repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'kana/vim-textobj-user'
